### PR TITLE
1.4.9 mac update

### PR DESCRIPTION
**Pull request by MacMillan-M**
Added dropzones for new objs to the CTLD script. CTLD.lua

Added new triggers and flags 106 and 777.
106 - For new broadcast message to join SRS.
777 - Radio option sets flag on or off. Off for regular restarts, on for delayed restart. First iteration, keep an eye out for bugs.

Last commit was to remove required modules. Should still be running the pingoo option file (new master option file)

### CODE REVIEW

**Comment by MacMillan-M** [comment]
Also changed AWACS to E3s instead of E2s.

**Comment by MacMillan-M** [comment]
Radio menu changes confirmed not working. Need assistance from pingoo to fix.

**Comment by pingoocoder** [comment]
Regarding 777, whos allowed to change this? Only 7cav members or everyone? We should restrict access.

**Comment by MacMillan-M** [comment]
> Regarding 777, whos allowed to change this? Only 7cav members or everyone? We should restrict access.
> 
Currently everyone, not sure how to restrict access on it. Any ideas?
> "Also changed AWACS to E3s instead of E2s." please test to make sure Overlord gets to take off at Krymsk fine. We had instances where it gets stuck on the ramp as there isn't enough turning radius.
Rog will test
> 
> "Radio menu changes confirmed not working. Need assistance from pingoo to fix." May you provide details on this?
Fixed this one

**Comment by MacMillan-M** [comment]
Tested, called in AWACS via support, operates at altitude. Not sure how to call in the Krymsk AWACS though.

**Comment by pingoocoder** [comment]
> Currently everyone, not sure how to restrict access on it. Any ideas?
Create a passworded (hidden) admin slot and have this radio option only available to that group.

> Tested, called in AWACS via support, operates at altitude. Not sure how to call in the Krymsk AWACS though.
For now can you enable on your mission editor the object visual and roughly measure the parking spot with the E3 to see if it has a wide (clear) enough route onto the runway? Otherwise, you might need to change its parking spot.

**Comment by MacMillan-M** [comment]
> 

AWACS spawns in air. Krym7 has enough room so should be good. 

Ive added an F18 at anapa, hot. Unitname Admin-1, pilot name Admin-1-1

Need to dig into finding the groupID and then add that to the MOOSE file.

**Comment by pingoocoder** [comment]
Remember to update "Foothold_1.4.9" in ME. looks like restart does 1.4.8 still.

**Review by pingoocoder — APPROVED** [review]

**Pull request merged**
